# A Python3 script used for exporting protocol id mappings from
# registries.json generated by https://wiki.vg/Data_Generators
import json

mc_ver = '16'

with open(f'D:/Minecraft/Servers/MC{mc_ver}Pure/generated/reports/registries.json') as f:
    lines = f.read()

    itemList = { }
    
    dict = json.loads(lines)
    entries = dict['minecraft:entity_type']['entries']

    with open(f'Extra Data/entity_types_code-1.{mc_ver}.txt', 'w+') as out:
        for key, value in entries.items():
            itemList[value['protocol_id']] = key
            print(f'[{value["protocol_id"]}] {key}')
            code = f'public static readonly ResourceLocation {key.split(":")[1].upper()}_ID = new("{key}");\n'
            out.write(code)

    with open(f'Extra Data/entity_types-1.{mc_ver}.json', 'w+') as out:
        text = json.dumps(itemList, indent=4, separators=(',', ': '))
        out.write(text)